# Generated by Django 4.2.2 on 2023-09-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='numero_siniestro',
            field=models.BigIntegerField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
