# Generated by Django 4.2.2 on 2023-09-05 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgl', '0002_alter_licitacion_numero_siniestro'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgl.provincia'),
        ),
    ]
