# Generated by Django 4.2.2 on 2023-09-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgl', '0003_licitacion_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='preparado',
            field=models.BooleanField(default=False),
        ),
    ]
