# Generated by Django 4.2.2 on 2023-09-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgl', '0004_licitacion_enviado_licitacion_preparado'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='listo',
            field=models.BooleanField(default=False),
        ),
    ]
