# Generated by Django 4.2.7 on 2024-01-28 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0001_initial'),
        ('seguros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='direccion.localidad'),
        ),
        migrations.AddField(
            model_name='transporte',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='direccion.localidad'),
        ),
    ]
