# Generated by Django 4.2.7 on 2024-01-28 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0002_taller_localidad_transporte_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobada',
            name='numero_nota_pedido',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='aprobada',
            name='numero_orden_compra',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='cantidad_articulos',
            field=models.DecimalField(decimal_places=0, max_digits=4, unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='costo_transporte',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='numero_presupuesto',
            field=models.DecimalField(decimal_places=0, max_digits=20, unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='numero_siniestro',
            field=models.DecimalField(decimal_places=0, max_digits=20, unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='preparada',
            name='cantidad_articulos_listos',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
